/**
 * Virtual Memory Simulator — Type Definitions
 *
 * All shared types live here. One file, no fragmentation.
 */

// ─── Algorithm Identifiers ───────────────────────────────────

export type AlgorithmId = 'fifo' | 'lru' | 'optimal' | 'clock';

export interface AlgorithmInfo {
  id: AlgorithmId;
  name: string;
  shortName: string;
  description: string;
  /** One-sentence explanation of the eviction strategy */
  strategy: string;
}

// ─── Memory Access ───────────────────────────────────────────

export interface Access {
  pid: number;
  page: number;
  write: boolean;
}

// ─── Frame State ─────────────────────────────────────────────

export interface FrameState {
  frameId: number;
  page: number | null;
  pid: number | null;
  dirty: boolean;
  referenced: boolean;
  loadedAtStep: number;       // Step when this page was loaded
  lastAccessedAtStep: number; // Step when this page was last accessed
}

// ─── Simulation Step ─────────────────────────────────────────

export interface SimulationStep {
  step: number;               // 1-indexed step number
  access: Access;             // The page access at this step
  frames: FrameState[];       // State of all frames AFTER this step
  hit: boolean;               // Was the page already in memory?
  pageFault: boolean;         // Did a page fault occur?
  evictedPage: number | null; // Page number that was evicted (null if no eviction)
  evictedPid: number | null;  // PID of evicted page
  evictedDirty: boolean;      // Was evicted page dirty?
  loadedIntoFrame: number;    // Frame index where new page was loaded (-1 if hit)
  explanation: string;        // Human-readable: "Page 5 was evicted because..."
  internalState?: any;        // Algorithm-specific state for visualization
  cumulativeStats: {
    faults: number;
    hits: number;
    hitRatio: number;
    evictions: number;
  };
}

// ─── Simulation Result ───────────────────────────────────────

export interface SimulationResult {
  steps: SimulationStep[];
  algorithm: AlgorithmId;
  numFrames: number;
  totalAccesses: number;
  totalFaults: number;
  totalHits: number;
  hitRatio: number;
  totalEvictions: number;
}

// ─── Scenario ────────────────────────────────────────────────

export interface Scenario {
  id: string;
  name: string;
  description: string;
  educationalNote: string;
  accesses: Access[];
  recommendedFrames: number;
}

// ─── Algorithm Interface ─────────────────────────────────────

export interface VictimSelection {
  frameIndex: number;
  explanation: string;
}

/**
 * All page replacement algorithms implement this interface.
 *
 * The key design decision: selectVictim() returns BOTH a frame index
 * AND a human-readable explanation. This means educational text is
 * generated by the algorithm itself, not parsed from action strings.
 */
export interface PageReplacementAlgorithm {
  id: AlgorithmId;

  /** Called once before simulation starts */
  initialize(numFrames: number, allAccesses: Access[]): void;

  /** Pick which frame to evict. Only called when all frames are occupied. */
  selectVictim(frames: FrameState[], currentStep: number): VictimSelection;

  /** Called when an existing page is accessed (hit) */
  onAccess(frameIndex: number, step: number): void;

  /** Called when a new page is loaded into a frame */
  onPageIn(frameIndex: number, step: number): void;

  /** Return internal state for visualization */
  getState(): any;

  /** Reset internal state for reuse */
  reset(): void;
}
